name: Deploy app
run-name: Deployment done by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      env:
        description: AWS env to deploy to
        required: true
        default: "staging"
        type: choice
        options:
          - staging
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: ["18.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Clean install project
        run: npm ci && npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::362001164764:role/deployer
          aws-region: us-east-1
      - name: Deploy app
        run: npx sst deploy --stage nz-staging